### ISSUE TITLE
Gemspec email

### ISSUE THREAD

**Issue by alkrauss48** [brightbit/markdown_checkboxes#2]
I inserted my email in the gemspec email since I didn't think this was something we wanted to use for the hello@brightbit.com alias. I may be wrong in assuming that though. Do we have a preferred email we want to change it to?

**Comment by ericboehs** [comment]
hello@brightb.it should be correct. We probably should switch ruby gems to
use hello@brightbit.com though. (Update the existing account we have.)

**Comment by alkrauss48** [comment]
Switched the account to hello@brightbit.com. Gravatar needs to be updated for that email though.
