### ISSUE TITLE
Rubygems Account

### ISSUE THREAD

**Issue by alkrauss48** [brightbit/markdown_checkboxes#3]
Here's the link for the gem:

https://rubygems.org/gems/redcarpet_checkboxes

I put it under hello@brightbit.com. Do we want to change that? I tried to put it under hello@brightb.it, but it looks like an account for that email was already created and the password information wasn't in lastpass, so I couldn't log into that

**Comment by vlucas** [comment]
Yes we do have an account already at https://rubygems.org/profiles/brightbit that we released AstroChimp under, but I am not sure the login. We may have to go through the password reset process on that.

**Comment by vlucas** [comment]
@ericboehs published that gem, so he may have it

**Comment by ericboehs** [comment]
I moved it to the Brightbit Vault (1Password). @aaron we can get you set up
on this tomorrow.

**Comment by alkrauss48** [comment]
Gem has been moved to Brightbit's account, also where astrochimp resides. I changed the username to hello@brightbit.com, so remember that if you login.

New gem url: https://rubygems.org/gems/markdown_checkboxes
