### ISSUE TITLE
Gem Name Change

### ISSUE THREAD

**Issue by alkrauss48** [brightbit/markdown_checkboxes#5]
@ericboehs mentioned to me about changing the name to `markdown_checkboxes`, to enhance search-ability and so people know what it is right on the dot. I think that may be a good idea.

I had initially chosen to keep redcarpet in the name so it was obvious that it was an addon to that gem, but many people may not know what redcarpet is, let alone to search for another gem with the name related to checkbox parsing.

**Comment by vlucas** [comment]
I think that's a good idea actually - and will certainly enhance searchability.

**Comment by alkrauss48** [comment]
Name has been changed to `markdown_checkboxes`

New gem url: https://rubygems.org/gems/markdown_checkboxes
