### ISSUE TITLE
Display each checkbox on its own line?

### ISSUE THREAD

**Issue by joefiorini** [brightbit/markdown_checkboxes#6]
How do you display each checkbox on its own line with this gem? Is there a magic CSS incantation or something else you do for this?

**Comment by alkrauss48** [comment]
There's a couple ways you can do it.
1. You can use CSS just like you mentioned (probably just by giving it a `display: block;` style), as the checkboxes will all get turned into standard `<input type="checkbox" ... />` tags.
2. By default, Redcarpet (the markdown parser we use) allows you to throw html tags into your markdown, so you can use a standard `<br>` tag. This is probably not the best option if you are having users input the markdown.
3. This is the easiest option. You can specify some renderer options when you initialize your renderer, and the `:hard_wrap` option is what you want here. This will insert HTML `<br>` tags inside on paragraphs where the origin Markdown document had newlines, so anywhere you have a newline in your Markdown, there will be a new line in the displayed text.

Here's how to initialize a renderer with that option:

``` ruby
parser = CheckboxMarkdown.new( Redcarpet::Render::HTML.new(:hard_wrap => true) )
```

A bunch of other options are available as well that allow you to customize your rendering, see the [Redcarpet github page](https://github.com/vmg/redcarpet) to see them all.

**Comment by joefiorini** [comment]
The `display: block` option doesn't work; since the label isn't in a tag itself the checkbox displays on a line and the text is on the next line.

I'll try the hard break, but it would be really nice if each checkbox and its associated text was wrapped in an `<li>`, with the entire list in a `<ul>`. This is how Github's checkbox lists render. What do you think about that?

**Comment by alkrauss48** [comment]
Ah, I didn't think about the label for the checkbox. The hard_wrap option should work for what you're needing, but I see the benefit of putting each series of checkboxes and associated labels inside of an `<li>`, especially for stylistic purposes if we throw a default class on there as well.

I'll look into this and see how difficult it would be to implement, and if it would interfere with how Redcarpet handles the hard_wrap option - among other options. We would probably want to add an option on the parser in case the developer didn't want the checkboxes in a list; something like `:list => false` perhaps.

I hope the hard_wrap option solves your problem, and thank for your thoughts on this. Feel free to hack on too if you have other ideas
